### ISSUE TITLE
Customization 

### ISSUE THREAD

**Issue by old-izayoi** [ArmandPhilippot/coldark-firefox#1]
Is there any way to change the default colors for each theme? With which program i can edit the xpi file? 
also, does this work as firefox color theme is there any difference between the addon and traditional theme?

**Comment by ArmandPhilippot** [comment]
First, thank you for your interest in Coldark Firefox!

No, the default color cannot be changed. This extension reuses the colors of Coldark, there are no plans to use other colors.

The xpi file is not editable, it is an archive (like `zip`) allowing installation in Firefox. This is a signed archive. All colors are defined in the [background.js file](https://github.com/ArmandPhilippot/coldark-firefox/blob/main/assets/js/background.js). To achieve this, since you also need to change the information in manifest.json, I only see the creation of a [new extension](https://extensionworkshop.com/documentation/themes/).

I'm not sure I understand your last question. If by addon you are referring to Coldark Firefox, then yes. Everything is detailed in the [readme](https://github.com/ArmandPhilippot/coldark-firefox#readme). Colors are unique to Coldark. And there is a switch system between the light version and the dark version.
